--========================================
--ADMINISTRATIVO

CREATE TABLE EMPLEADOS (
EMPL_CEDULA_V VARCHAR(20) NOT NULL,
EMPL_AREA_INT INTEGER,
EMPL_ESTADO_V CHAR(2) NOT NULL
)
ON "DEFAULT"
GO


ALTER TABLE EMPLEADOS ADD CHECK(EMPL_ESTADO_V IN ('A','I') );

ALTER TABLE EMPLEADOS ADD CONSTRAINT EMPLEADOS_PK PRIMARY KEY CLUSTERED (EMPL_CEDULA_V)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE EMPRESAS (
EMPRE_NIT_V VARCHAR(50) NOT NULL,
EMPRE_RAZONSOCIAL_V VARCHAR(200) NOT NULL,
EMPRE_TELEFONO_V VARCHAR(10),
EMPRE_EMAIL_V CHAR(200)
)
;

ALTER TABLE EMPRESAS ADD CONSTRAINT EMPRESAS_PK PRIMARY KEY CLUSTERED (EMPRE_NIT_V)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE OFICINAEMPLEADOS (
OFEM_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
OFEM_OFICINA_INT INTEGER NOT NULL,
OFEM_EMPLEADO_V VARCHAR(20) NOT NULL
)
;

ALTER TABLE OFICINAEMPLEADOS ADD CONSTRAINT OFICINAEMPLEADOS_PK PRIMARY KEY CLUSTERED (OFEM_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE OFICINAS (
OFIC_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
OFIC_NOMBRE_V VARCHAR(200) NOT NULL,
OFIC_DIRECCION_V VARCHAR(200) NOT NULL,
OFIC_ADMINISTRADOR_V VARCHAR(20) NOT NULL
)
;

ALTER TABLE OFICINAS ADD CONSTRAINT OFICINAS_PK PRIMARY KEY CLUSTERED (OFIC_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE PERSONAS (
PERS_CEDULA_V VARCHAR(20) NOT NULL,
PERS_NOMBRES_V VARCHAR(200) NOT NULL,
PERS_APELLIDOS_V VARCHAR(200) NOT NULL
)
;

ALTER TABLE PERSONAS ADD CONSTRAINT PERSONAS_PK PRIMARY KEY CLUSTERED (PERS_CEDULA_V)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE PROVEDORES (
PROV_ID_V VARCHAR(50) NOT NULL,
PROV_TIPOPROV_V CHAR(2) NOT NULL,
PROV_PERSONA_V VARCHAR(20),
PROV_EMPRESA_V VARCHAR(50)
)
ON "DEFAULT"
GO


ALTER TABLE PROVEDORES ADD CHECK(PROV_TIPOPROV_V IN('J','N'));

ALTER TABLE PROVEDORES ADD CONSTRAINT PROVEDORES_PK PRIMARY KEY CLUSTERED (PROV_ID_V)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
ON "DEFAULT"
GO
ALTER TABLE PROVEDORES ADD CONSTRAINT PROVEDORES__PERS_UN UNIQUE NONCLUSTERED (PROV_PERSONA_V)
ON "DEFAULT"
GO
ALTER TABLE PROVEDORES ADD CONSTRAINT PROVEDORES__EMPREUN UNIQUE NONCLUSTERED(PROV_EMPRESA_V)
;
--========================================

--========================================
--INVENTARIO

CREATE TABLE ASIGNACION_DISPOSITIVOS (
ASDP_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
ASDP_OFICID_INT INTEGER NOT NULL,
ASDP_DISPOSITIVO_V VARCHAR(200) NOT NULL,
ASDP_EMPLEADO_V VARCHAR(20) NOT NULL,
ASDP_TIPOUSO_V CHAR(2) NOT NULL,
ASDP_FECASIGNA_DATE DATE NOT NULL,
ASDP_FECRETIRO_DATE DATE,
ASDP_ESTADOASIGNA_V CHAR(2) NOT NULL,
ASDP_DESCRIP_V VARCHAR(200)
)
ON "DEFAULT"
GO


ALTER TABLE ASIGNACION_DISPOSITIVOS
ADD
CHECK ( ASDP_TIPOUSO_V IN ('C', 'I') )
GO


ALTER TABLE ASIGNACION_DISPOSITIVOS ADD CHECK(ASDP_ESTADOASIGNA_V IN ('A','R') );

ALTER TABLE ASIGNACION_DISPOSITIVOS ADD CONSTRAINT ASIGNACION_DISPOSITIVOS_PK PRIMARY KEY CLUSTERED (ASDP_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE BODEGAS (
BODE_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
BODE_DESC_V VARCHAR(200) NOT NULL,
BODE_UBICACION_INT INTEGER NOT NULL
)
;

ALTER TABLE BODEGAS ADD CONSTRAINT BODEGAS_PK PRIMARY KEY CLUSTERED (BODE_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE CATEGORIA_DISPOS (
CATD_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
CATD_DESC_V VARCHAR(200) NOT NULL
)
;

ALTER TABLE CATEGORIA_DISPOS ADD CONSTRAINT CATDISPO_PK PRIMARY KEY CLUSTERED (CATD_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE COMPUTADORES_DISPO (
COMP_SERIAL_V VARCHAR(200) NOT NULL,
COMP_RAMINSTALL_INT INTEGER NOT NULL
)
;

ALTER TABLE COMPUTADORES_DISPO ADD CONSTRAINT COMPUTADORES_PK PRIMARY KEY CLUSTERED (COMP_SERIAL_V)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE DETALLE_BAJAS (
DTBA_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
DTBA_BAJAINVENTARIO_INT INTEGER NOT NULL,
DTBA_TIPOELEMETO_V CHAR(2) NOT NULL,
INBA_DISPOSITIVO_V VARCHAR(200),
INBA_REPUESTO_INT INTEGER
)
ON "DEFAULT"
GO


ALTER TABLE DETALLE_BAJAS ADD CHECK(DTBA_TIPOELEMETO_V IN ('D','R') );

ALTER TABLE DETALLE_BAJAS ADD CONSTRAINT DETALLE_BAJAS_PK PRIMARY KEY CLUSTERED (DTBA_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
ON "DEFAULT"
GO
ALTER TABLE DETALLE_BAJAS ADD CONSTRAINT DETALLE_BAJAS_DISP_UN UNIQUE NONCLUSTERED (INBA_DISPOSITIVO_V)
ON "DEFAULT"
GO
ALTER TABLE DETALLE_BAJAS ADD CONSTRAINT DETALLE_BAJAS_REP_UN UNIQUE NONCLUSTERED(INBA_REPUESTO_INT)
ON "DEFAULT"
GO

CREATE TABLE DISPOSITIVOS
(
DISPO_SERIAL_V VARCHAR(200) NOT NULL,
DISPO_TIPOID_INT INTEGER NOT NULL,
DISPO_MARCA_INT INTEGER NOT NULL,
DISPO_MODELO_INT INTEGER NOT NULL,
DISPO_DESC_V VARCHAR(200),
DISPO_ESTADOUSO_V CHAR(2) NOT NULL DEFAULT 'N' ,
DISPO_ESTADODISPO_V CHAR (2) NOT NULL DEFAULT 'L' ,
DISPO_ESTADOINVET_V CHAR (2) NOT NULL DEFAULT 'A'
)
ON "DEFAULT"
GO


ALTER TABLE DISPOSITIVOS
ADD
CHECK ( DISPO_ESTADOUSO_V IN ('N', 'U') )
GO


ALTER TABLE DISPOSITIVOS
ADD
CHECK ( DISPO_ESTADODISPO_V IN ('L', 'O') )
GO


ALTER TABLE DISPOSITIVOS ADD CHECK(DISPO_ESTADOINVET_V IN ('A','D') );

ALTER TABLE DISPOSITIVOS ADD CONSTRAINT DISPOSITIVOS_PK PRIMARY KEY CLUSTERED (DISPO_SERIAL_V)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE HDD (
HDD_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
HDD_INTERFAZHDD_INT INTEGER NOT NULL,
HDD_CAPALMACENA_INT INTEGER NOT NULL,
HDD_RPM_INT INTEGER,
HDD_MARCA_INT INTEGER NOT NULL
)
;

ALTER TABLE HDD ADD CONSTRAINT HDD_PK PRIMARY KEY CLUSTERED (HDD_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE HDD_PC (
HDPC_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
HDPC_PC_V VARCHAR(200) NOT NULL,
HDPC_HDDID_INT INTEGER NOT NULL
)
;

ALTER TABLE HDD_PC ADD CONSTRAINT HDD_PC_PK PRIMARY KEY CLUSTERED (HDPC_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE IMPRESORAS_DISPO (
IMPR_SERIAL_V VARCHAR(200) NOT NULL,
IMPR_LAN_INT INTEGER,
IMPR_WIFI_INT INTEGER,
IMPR_SUMINISTRO_INT INTEGER NOT NULL
)
;

ALTER TABLE IMPRESORAS_DISPO ADD CONSTRAINT IMPRESORAS_PK PRIMARY KEY CLUSTERED (IMPR_SERIAL_V)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE INTERFAZ_HDD (
INHD_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
INHD_DESC_V VARCHAR(200) NOT NULL
)
;

ALTER TABLE INTERFAZ_HDD ADD CONSTRAINT INTERFAZHDD_PK PRIMARY KEY CLUSTERED (INHD_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE INVENTARIO_BAJAS (
INBA_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
INBA_CONCEPTO_V CHAR(2) DEFAULT 'DF',
INBA_TIPOELEMETO_V CHAR(2) NOT NULL,
INBA_FECHABAJA_DATE DATE NOT NULL,
INBA_TIPOBENEFI_INT INTEGER,
INBA_PERSONA_V VARCHAR(20),
INBA_EMPRESADONA_V VARCHAR(50),
INBA_PROVDISPOF_V VARCHAR(50),
INBA_DESCRICION_V VARCHAR(200)
)
ON "DEFAULT"
GO


ALTER TABLE INVENTARIO_BAJAS
ADD
CHECK ( INBA_CONCEPTO_V IN ('DF', 'DO') )
GO


ALTER TABLE INVENTARIO_BAJAS ADD CHECK(INBA_TIPOELEMETO_V IN ('D','R') );

ALTER TABLE INVENTARIO_BAJAS ADD CONSTRAINT INVENTARIO_BAJAS_PK PRIMARY KEY CLUSTERED (INBA_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE INVENTARIO_BODEGA (
INVBO_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
INVBO_BODEGA_INT INTEGER NOT NULL,
INVBO_SERIALDISPO_V VARCHAR(200),
INVBO_IDREPUESTO_INT INTEGER,
INVBO_TIPOELEMENTO_V CHAR(2) NOT NULL,
INVBO_FECINGRESO_DATE DATE NOT NULL,
INVBO_FECSALIDA_DATE DATE NOT NULL,
INVBO_ESTADOBOD_V CHAR(2) NOT NULL,
INVBO_DESC_V VARCHAR(200)
)
ON "DEFAULT"
GO


ALTER TABLE INVENTARIO_BODEGA
ADD
CHECK ( INVBO_TIPOELEMENTO_V IN ('D', 'R') )
GO


ALTER TABLE INVENTARIO_BODEGA ADD CHECK(INVBO_ESTADOBOD_V IN ('I','R') );

ALTER TABLE INVENTARIO_BODEGA ADD CONSTRAINT DISPOSITIVOS_BODEGA_PKV2 PRIMARY KEY CLUSTERED (INVBO_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE MARCAS (
MARC_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
MARC_DESC_V VARCHAR(200) NOT NULL
)
;

ALTER TABLE MARCAS ADD CONSTRAINT MARCA_DISPOSITIVOS_PK PRIMARY KEY CLUSTERED (MARC_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE MODELOS (
MODD_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
MODD_DESC_V VARCHAR(200) NOT NULL
)
;

ALTER TABLE MODELOS ADD CONSTRAINT MODELOS_PK PRIMARY KEY CLUSTERED (MODD_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE MONITORES_DISPO (
MONI_SERIAL_V VARCHAR(200) NOT NULL,
MONI_TIPO_V VARCHAR(200) NOT NULL,
MONI_TPULGADAS_INT INTEGER,
MONI_PVGA_INT INTEGER,
MONI_PDHMI_INT INTEGER,
MONI_PDVI_INT INTEGER,
MONI_PDP_INT INTEGER,
MONI_PUSB_INT INTEGER
)
;

ALTER TABLE MONITORES_DISPO ADD CONSTRAINT MONITORES_PK PRIMARY KEY CLUSTERED (MONI_SERIAL_V)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE PROCESADORES (
PROS_ID_IN INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
PROS_DESC_V VARCHAR(200) NOT NULL,
PROS_FABRICANTE_INT INTEGER NOT NULL,
PROS_FREC_V VARCHAR(20),
PORC_NUCLEOS_INT INTEGER
)
;

ALTER TABLE PROCESADORES ADD CONSTRAINT PROCESADORES_PK PRIMARY KEY CLUSTERED (PROS_ID_IN)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE PROCESADORES_PCS (
PRPC_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
PRPC_PROCESADOR_INT INTEGER NOT NULL,
PRPC_COMPUTADOR_V VARCHAR(200) NOT NULL
)
;

ALTER TABLE PROCESADORES_PCS ADD CONSTRAINT PROCESADORES_PCS_PK PRIMARY KEY CLUSTERED (PRPC_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE RED_DISPO (
DRED_SERIAL_V VARCHAR(200) NOT NULL,
DRED_VELOCIDAD_INT INTEGER,
DRED_BANDAS_V VARCHAR(200),
DRED_CATEGORIA_V VARCHAR(200),
DRED_PUERTOS_INT INTEGER,
DRED_ADMINIS_INT INTEGER
)
;

ALTER TABLE RED_DISPO ADD CONSTRAINT RED_PK PRIMARY KEY CLUSTERED (DRED_SERIAL_V)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE TIPOSREPUESTOS (
TPRP_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
TPRP_DESC_V VARCHAR(200)
)
;

ALTER TABLE TIPOSREPUESTOS ADD CONSTRAINT TIPOSREPUESTOS_PK PRIMARY KEY CLUSTERED (TPRP_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE REPUESTOS (
REPU_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
REPU_SERIAL_V VARCHAR(200),
REPU_MARCA_INT INTEGER,
REPU_MODELO_INT INTEGER,
REPU_TIPOC_INT INTEGER NOT NULL,
REPU_OBSERVA_V CHAR(500),
REPU_ESTADOUSO_V CHAR(2) NOT NULL,
REPU_ESTADODISPO_V CHAR(2),
REPU_ESTADOINVET_V CHAR(2)
)
;

ALTER TABLE REPUESTOS ADD CONSTRAINT REPUESTOS_PK PRIMARY KEY CLUSTERED (REPU_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE REPUESTOS_COMPATIBLES (
RECO_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
RECO_REPUESTO_INT INTEGER NOT NULL,
RECO_MODELO_INT INTEGER NOT NULL,
RECO_CATEGOTIA_INT INTEGER NOT NULL
)
;

ALTER TABLE REPUESTOS_COMPATIBLES ADD CONSTRAINT REPUESTOS_COMPATIBLES_PK PRIMARY KEY CLUSTERED (RECO_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE SUMINISTROS_IMPRE (
CONS_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
CONS_TIPO_V VARCHAR(200) NOT NULL,
CONS_CAPACIDAD_INT INTEGER NOT NULL,
CONS_DESC_V VARCHAR(200)
)
;

ALTER TABLE SUMINISTROS_IMPRE ADD CONSTRAINT SUMINISTROS_PK PRIMARY KEY CLUSTERED (CONS_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE TIPO_DISPOSITIVOS (
TPD_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
TPD_DESC_V VARCHAR(200) NOT NULL,
TPD_CATTIPO_INT INTEGER NOT NULL
)
;

ALTER TABLE TIPO_DISPOSITIVOS ADD CONSTRAINT TIPODISPOSITIVOS_PK PRIMARY KEY CLUSTERED (TPD_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

;
--========================================

--========================================
--SISTEMA

CREATE TABLE DOCUMENTOS (
DOCU_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
DOCU_NOMBRE_V VARCHAR(200) NOT NULL,
DOCU_NOMBREARCHIVO_V VARCHAR(200) NOT NULL,
DOCU_RUTAARCHIVO_V VARCHAR(200),
DOCU_MIME_V VARCHAR(200),
DOCU_FECMODIF_DATE DATE
)
;

ALTER TABLE DOCUMENTOS ADD CONSTRAINT DOCUMENTOS_PK PRIMARY KEY CLUSTERED (DOCU_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE OPERACION_DOCUMENTOS (
OPDC_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
OPDC_OPRACION_INT INTEGER NOT NULL,
OPDC_DOCUMENTO_INT INTEGER NOT NULL,
OPDC_ACTABAJA_INT INTEGER
)
;

ALTER TABLE OPERACION_DOCUMENTOS ADD CONSTRAINT OPERACION_DOCUMENTOS_PK PRIMARY KEY CLUSTERED (OPDC_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE ROLUSUARIOS (
ROL_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
ROL_DESC_V VARCHAR(200) NOT NULL
)
;

ALTER TABLE ROLUSUARIOS ADD CONSTRAINT ROLUSUARIOS_PK PRIMARY KEY CLUSTERED (ROL_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE TRANSDOCSCARGADOS (
TDOC_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
TDOC_DESC_V VARCHAR(200) NOT NULL
)
;

ALTER TABLE TRANSDOCSCARGADOS ADD CONSTRAINT TRANSDOCSCARGADOS_PK PRIMARY KEY CLUSTERED (TDOC_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
;

CREATE TABLE USUARIOS (
USUA_ID_INT INTEGER NOT NULL IDENTITY NOT FOR REPLICATION,
USUA_NICNAME_V VARCHAR(200) NOT NULL,
USUA_CONTASEÑA_V VARCHAR(200) NOT NULL,
USUA_ROLSISTEMA_INT INTEGER NOT NULL,
USUA_ORIGEN_V INTEGER NOT NULL
)
ON "DEFAULT"
GO


ALTER TABLE USUARIOS ADD CHECK(USUA_ORIGEN_V IN (1,2) );

ALTER TABLE USUARIOS ADD CONSTRAINT USUARIOS_PK PRIMARY KEY CLUSTERED (USUA_ID_INT)
WITH (
ALLOW_PAGE_LOCKS = ON ,
ALLOW_ROW_LOCKS = ON )
ON "DEFAULT"
GO
ALTER TABLE USUARIOS ADD CONSTRAINT USUARIOS__UN UNIQUE NONCLUSTERED(USUA_NICNAME_V)
;
--========================================

--==========================================
--****RELACIONES:*******
-------------------------------------------------------------------------------------
--ADMINISTRATIVO:

ALTER TABLE EMPLEADOS
ADD CONSTRAINT EMPLEADOS_PERSONAS_FK FOREIGN KEY ( EMPL_CEDULA_V )
REFERENCES PERSONAS ( PERS_CEDULA_V )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE OFICINAEMPLEADOS
ADD CONSTRAINT OFICINATRABAJA_EMPLEADOS_FK FOREIGN KEY ( OFEM_EMPLEADO_V )
REFERENCES EMPLEADOS ( EMPL_CEDULA_V )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE OFICINAEMPLEADOS
ADD CONSTRAINT OFICINATRABAJA_OFICINAS_FK FOREIGN KEY ( OFEM_OFICINA_INT )
REFERENCES OFICINAS ( OFIC_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PROVEDORES
ADD CONSTRAINT PROVEDORES_EMPRESAS_FK FOREIGN KEY ( PROV_EMPRESA_V )
REFERENCES EMPRESAS ( EMPRE_NIT_V )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PROVEDORES
ADD CONSTRAINT PROVEDORES_PERSONAS_FK FOREIGN KEY ( PROV_PERSONA_V )
REFERENCES PERSONAS ( PERS_CEDULA_V )
ON DELETE NO ACTION
ON UPDATE NO ACTION;
-------------------------------------------------------------------------------------


-------------------------------------------------------------------------------------
--INVENTARIO

ALTER TABLE ASIGNACION_DISPOSITIVOS
ADD CONSTRAINT ASIGDISPO_DISPOSITIVOS_FK FOREIGN KEY ( ASDP_DISPOSITIVO_V )
REFERENCES DISPOSITIVOS ( DISPO_SERIAL_V )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE ASIGNACION_DISPOSITIVOS
ADD CONSTRAINT ASIGDISPO_EMPLEADOS_FK FOREIGN KEY ( ASDP_EMPLEADO_V )
REFERENCES EMPLEADOS ( EMPL_CEDULA_V )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE BODEGAS
ADD CONSTRAINT BODEGAS_OFICINAS_FK FOREIGN KEY ( BODE_UBICACION_INT )
REFERENCES OFICINAS ( OFIC_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE COMPUTADORES_DISPO
ADD CONSTRAINT COMPUTADORES_DISPOSITIVOS_FK FOREIGN KEY ( COMP_SERIAL_V )
REFERENCES DISPOSITIVOS ( DISPO_SERIAL_V )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE DETALLE_BAJAS
ADD CONSTRAINT DETBAJAS_DISPOSITIVOS_FK FOREIGN KEY ( INBA_DISPOSITIVO_V )
REFERENCES DISPOSITIVOS ( DISPO_SERIAL_V )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE DETALLE_BAJAS
ADD CONSTRAINT DETBAJAS_INVBAJAS_FK FOREIGN KEY ( DTBA_BAJAINVENTARIO_INT )
REFERENCES INVENTARIO_BAJAS ( INBA_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE DETALLE_BAJAS
ADD CONSTRAINT DETBAJAS_REPUESTOS_FK FOREIGN KEY ( INBA_REPUESTO_INT )
REFERENCES REPUESTOS ( REPU_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE DISPOSITIVOS
ADD CONSTRAINT DISPOSITIVOS_MARCAS_FK FOREIGN KEY ( DISPO_MARCA_INT )
REFERENCES MARCAS ( MARC_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE DISPOSITIVOS
ADD CONSTRAINT DISPOSITIVOS_MODELOSDIS_FK FOREIGN KEY ( DISPO_MODELO_INT )
REFERENCES MODELOS ( MODD_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE DISPOSITIVOS
ADD CONSTRAINT DISPOSITIVOS_TIPOSDISPO_FK FOREIGN KEY ( DISPO_TIPOID_INT )
REFERENCES TIPO_DISPOSITIVOS ( TPD_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE HDD
ADD CONSTRAINT HDD_INTERFAZHDD_FK FOREIGN KEY ( HDD_INTERFAZHDD_INT )
REFERENCES INTERFAZ_HDD ( INHD_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE HDD
ADD CONSTRAINT HDD_MARCAS_FK FOREIGN KEY ( HDD_MARCA_INT )
REFERENCES MARCAS ( MARC_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE HDD_PC
ADD CONSTRAINT HDD_PC_COMPUTADORES_DISPO_FK FOREIGN KEY ( HDPC_PC_V )
REFERENCES COMPUTADORES_DISPO ( COMP_SERIAL_V )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE HDD_PC
ADD CONSTRAINT HDD_PC_HDD_FK FOREIGN KEY ( HDPC_HDDID_INT )
REFERENCES HDD ( HDD_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE IMPRESORAS_DISPO
ADD CONSTRAINT IMPRESORAS_DISPOSITIVOS_FK FOREIGN KEY ( IMPR_SERIAL_V )
REFERENCES DISPOSITIVOS ( DISPO_SERIAL_V )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE IMPRESORAS_DISPO
ADD CONSTRAINT IMPRESORAS_SUMINISTROS_FK FOREIGN KEY ( IMPR_SUMINISTRO_INT )
REFERENCES SUMINISTROS_IMPRE ( CONS_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE INVENTARIO_BAJAS
ADD CONSTRAINT INVBAJAS_EMPRESAS_FK FOREIGN KEY ( INBA_EMPRESADONA_V )
REFERENCES EMPRESAS ( EMPRE_NIT_V )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE INVENTARIO_BAJAS
ADD CONSTRAINT INVBAJAS_PERSONAS_FK FOREIGN KEY ( INBA_PERSONA_V )
REFERENCES PERSONAS ( PERS_CEDULA_V )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE INVENTARIO_BAJAS
ADD CONSTRAINT INVBAJAS_PROVEDORES_FK FOREIGN KEY ( INBA_PROVDISPOF_V )
REFERENCES PROVEDORES ( PROV_ID_V )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE INVENTARIO_BODEGA
ADD CONSTRAINT INVENBODEGA_BODEGAS_FK FOREIGN KEY ( INVBO_BODEGA_INT )
REFERENCES BODEGAS ( BODE_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE INVENTARIO_BODEGA
ADD CONSTRAINT INVENBODEGA_DISPOSITIVOS_FK FOREIGN KEY ( INVBO_SERIALDISPO_V )
REFERENCES DISPOSITIVOS ( DISPO_SERIAL_V )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE INVENTARIO_BODEGA
ADD CONSTRAINT INVENBODEGA_REPUESTOS_FK FOREIGN KEY ( INVBO_IDREPUESTO_INT )
REFERENCES REPUESTOS ( REPU_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE MONITORES_DISPO
ADD CONSTRAINT MONITORES_DISPOSITIVOS_FK FOREIGN KEY ( MONI_SERIAL_V )
REFERENCES DISPOSITIVOS ( DISPO_SERIAL_V )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PROCESADORES_PCS
ADD CONSTRAINT PROCEPCS_PCS_FK FOREIGN KEY ( PRPC_COMPUTADOR_V )
REFERENCES COMPUTADORES_DISPO ( COMP_SERIAL_V )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PROCESADORES_PCS
ADD CONSTRAINT PROCEPCS_PROCES_FK FOREIGN KEY ( PRPC_PROCESADOR_INT )
REFERENCES PROCESADORES ( PROS_ID_IN )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PROCESADORES
ADD CONSTRAINT PROSESADORES_MARCAS_FK FOREIGN KEY ( PROS_FABRICANTE_INT )
REFERENCES MARCAS ( MARC_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;


ALTER TABLE RED_DISPO
ADD CONSTRAINT RED_DISPOSITIVOS_FK FOREIGN KEY ( DRED_SERIAL_V )
REFERENCES DISPOSITIVOS ( DISPO_SERIAL_V )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE REPUESTOS_COMPATIBLES
ADD CONSTRAINT REPUCOMP_CATDISPO_FK FOREIGN KEY ( RECO_CATEGOTIA_INT )
REFERENCES CATEGORIA_DISPOS ( CATD_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE REPUESTOS_COMPATIBLES
ADD CONSTRAINT REPUCOMP_MODELOS_FK FOREIGN KEY ( RECO_MODELO_INT )
REFERENCES MODELOS ( MODD_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE REPUESTOS_COMPATIBLES
ADD CONSTRAINT REPUCOMP_REPUESTOS_FK FOREIGN KEY ( RECO_REPUESTO_INT )
REFERENCES REPUESTOS ( REPU_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE REPUESTOS
ADD CONSTRAINT REPUESTOS_MARCAS_FK FOREIGN KEY ( REPU_MARCA_INT )
REFERENCES MARCAS ( MARC_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE REPUESTOS
ADD CONSTRAINT REPUESTOS_MODELOS_FK FOREIGN KEY ( REPU_MODELO_INT )
REFERENCES MODELOS ( MODD_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE REPUESTOS
ADD CONSTRAINT REPUESTOS_TIPOS_FK FOREIGN KEY ( REPU_TIPOC_INT )
REFERENCES TIPOSREPUESTOS ( TPRP_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE TIPO_DISPOSITIVOS
ADD CONSTRAINT TIPODISPO_CATDISPO_FK FOREIGN KEY ( TPD_CATTIPO_INT )
REFERENCES CATEGORIA_DISPOS ( CATD_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;
-------------------------------------------------------------------------------------


-------------------------------------------------------------------------------------
--SISTEMA:
ALTER TABLE OPERACION_DOCUMENTOS
ADD CONSTRAINT OPEDOCS_DOCUMENTOS_FK FOREIGN KEY ( OPDC_DOCUMENTO_INT )
REFERENCES DOCUMENTOS ( DOCU_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE OPERACION_DOCUMENTOS
ADD CONSTRAINT OPEDOCS_INVENTARIO_BAJAS_FK FOREIGN KEY ( OPDC_ACTABAJA_INT )
REFERENCES INVENTARIO_BAJAS ( INBA_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE OPERACION_DOCUMENTOS
ADD CONSTRAINT OPEDOCS_TIPOSDOCSCARGADOS_FK FOREIGN KEY ( OPDC_OPRACION_INT )
REFERENCES TRANSDOCSCARGADOS ( TDOC_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE USUARIOS
ADD CONSTRAINT USUARIOS_ROLUSUARIOS_FK FOREIGN KEY ( USUA_ROLSISTEMA_INT )
REFERENCES ROLUSUARIOS ( ROL_ID_INT )
ON DELETE NO ACTION
ON UPDATE NO ACTION;
-------------------------------------------------------------------------------------
--==========================================