/*SUBTIPODISPOSITIVOS*/

INSERT INTO SUBT_DISPOSITIVOS(STDP_DESC_V) VALUES('COMPUTADOR');
INSERT INTO SUBT_DISPOSITIVOS(STDP_DESC_V) VALUES('IMPRESORA');
INSERT INTO SUBT_DISPOSITIVOS(STDP_DESC_V) VALUES('MONITOR');
INSERT INTO SUBT_DISPOSITIVOS(STDP_DESC_V) VALUES('RED');
INSERT INTO SUBT_DISPOSITIVOS(STDP_DESC_V) VALUES('ELECTRICOS');
SELECT * FROM SUBT_DISPOSITIVOS;


/*TIPO_DISPOSITIVOS*/
INSERT INTO TIPO_DISPOSITIVOS(TPD_DESC_V,TPD_SUBTIPO_INT) VALUES('PORTATIL',1);
INSERT INTO TIPO_DISPOSITIVOS(TPD_DESC_V,TPD_SUBTIPO_INT) VALUES('ESCRITORIO',1);
INSERT INTO TIPO_DISPOSITIVOS(TPD_DESC_V,TPD_SUBTIPO_INT) VALUES('SERVIDOR',1);
INSERT INTO TIPO_DISPOSITIVOS(TPD_DESC_V,TPD_SUBTIPO_INT) VALUES('TABLETA',1);
SELECT * FROM TIPO_DISPOSITIVOS;

/*MARCAS*/
INSERT INTO MARCA_DISPOSITIVOS (MARC_DESC_V) VALUES('DELL');
INSERT INTO MARCA_DISPOSITIVOS (MARC_DESC_V) VALUES('LENOVO');
INSERT INTO MARCA_DISPOSITIVOS (MARC_DESC_V) VALUES('HP');
INSERT INTO MARCA_DISPOSITIVOS (MARC_DESC_V) VALUES('INTEL');
SELECT * FROM MARCA_DISPOSITIVOS;

/*MODELOS*/
INSERT INTO MODELOS_DISPOSITIVOS (MODD_DESC_V) VALUES('OPTIPLEX 380');
INSERT INTO MODELOS_DISPOSITIVOS (MODD_DESC_V) VALUES('VOSTRO 380');
INSERT INTO MODELOS_DISPOSITIVOS (MODD_DESC_V) VALUES('OPTIPLEX 790');
INSERT INTO MODELOS_DISPOSITIVOS (MODD_DESC_V) VALUES('SYSTEM X');
SELECT * FROM MODELOS_DISPOSITIVOS;


/*DISPOSITIVOS*/
INSERT INTO DISPOSITIVOS(DISPO_SERIAL_V,DISPO_TIPOID_INT,DISPO_MARCA_INT,DISPO_MODELO_INT,DISPO_ESTADO_INT,DISPO_DESC_V)VALUES('SERIAL1',2,1,3,'A','DISPOSITIVO NUEVO');
INSERT INTO DISPOSITIVOS(DISPO_SERIAL_V,DISPO_TIPOID_INT,DISPO_MARCA_INT,DISPO_MODELO_INT,DISPO_ESTADO_INT,DISPO_DESC_V)VALUES('SERIAL2',1,2,3,'A','DISPOSITIVO NUEVO');
INSERT INTO DISPOSITIVOS(DISPO_SERIAL_V,DISPO_TIPOID_INT,DISPO_MARCA_INT,DISPO_MODELO_INT,DISPO_ESTADO_INT,DISPO_DESC_V)VALUES('SERIAL3',3,3,3,'A','DISPOSITIVO NUEVO');
INSERT INTO DISPOSITIVOS(DISPO_SERIAL_V,DISPO_TIPOID_INT,DISPO_MARCA_INT,DISPO_MODELO_INT,DISPO_ESTADO_INT,DISPO_DESC_V)VALUES('SERIAL4',2,1,3,'A','DISPOSITIVO NUEVO');


/*COMPUTADORES*/
-- PROCESADORES
INSERT INTO PROCESADORES(PROS_DESC_V,PROS_FABRICANTE_INT,PROS_FREC_V,PORC_NUCLEOS_INT) VALUES('INTEL COR I7',4,'3.0 GHZ',7);
--INTERFAZ HDD
INSERT INTO INTERFAZ_HDD(INHD_DESC_V) VALUES('SATA');
INSERT INTO INTERFAZ_HDD(INHD_DESC_V) VALUES('IDE');
INSERT INTO INTERFAZ_HDD(INHD_DESC_V) VALUES('SAS');

INSERT INTO COMPUTADORES_DISPO(COMP_SERIAL_V,COMP_PROCESADOR_INT,COMP_TPALMACENAMIENTO_INT,COMP_CAPALMACENA_INT,COMP_CAPRAM_INT) VALUES('SERIAL2',1,1,500000,4000);


/*CONSULTAS*/
SELECT * FROM TIPO_DISPOSITIVOS;
SELECT * FROM SUBT_DISPOSITIVOS;
SELECT * FROM MARCA_DISPOSITIVOS;
SELECT * FROM MODELOS_DISPOSITIVOS;
SELECT * FROM DISPOSITIVOS;

SELECT        DISPOSITIVOS.DISPO_SERIAL_V, SUBT_DISPOSITIVOS.STDP_DESC_V, TIPO_DISPOSITIVOS.TPD_DESC_V, MARCA_DISPOSITIVOS.MARC_DESC_V, MODELOS_DISPOSITIVOS.MODD_DESC_V, 
                         PROCESADORES.PROS_DESC_V, PROCESADORES.PROS_FREC_V, PROCESADORES.PORC_NUCLEOS_INT, INTERFAZ_HDD.INHD_DESC_V, COMPUTADORES_DISPO.COMP_CAPALMACENA_INT, 
                         COMPUTADORES_DISPO.COMP_CAPRAM_INT, DISPOSITIVOS.DISPO_ESTADO_INT, DISPOSITIVOS.DISPO_DESC_V
FROM            DISPOSITIVOS INNER JOIN
                         COMPUTADORES_DISPO ON DISPOSITIVOS.DISPO_SERIAL_V = COMPUTADORES_DISPO.COMP_SERIAL_V INNER JOIN
                         TIPO_DISPOSITIVOS ON DISPOSITIVOS.DISPO_TIPOID_INT = TIPO_DISPOSITIVOS.TPD_ID_INT INNER JOIN
                         SUBT_DISPOSITIVOS ON TIPO_DISPOSITIVOS.TPD_SUBTIPO_INT = SUBT_DISPOSITIVOS.STDP_ID_INT INNER JOIN
                         PROCESADORES ON COMPUTADORES_DISPO.COMP_PROCESADOR_INT = PROCESADORES.PROS_ID_IN INNER JOIN
                         INTERFAZ_HDD ON COMPUTADORES_DISPO.COMP_TPALMACENAMIENTO_INT = INTERFAZ_HDD.INHD_ID_INT INNER JOIN
                         MARCA_DISPOSITIVOS ON DISPOSITIVOS.DISPO_MARCA_INT = MARCA_DISPOSITIVOS.MARC_ID_INT INNER JOIN
                         MODELOS_DISPOSITIVOS ON DISPOSITIVOS.DISPO_MODELO_INT = MODELOS_DISPOSITIVOS.MODD_ID_INT;