/*BORRAR TABLAS*/
/**/
DROP TABLE COMPUTADORES_DISPO;
DROP TABLE DISPOSITIVOS;
DROP TABLE IMPRESORAS_DISPO;
DROP TABLE INTERFAZ_HDD;
DROP TABLE MARCA_DISPOSITIVOS;
DROP TABLE MODELOS_DISPOSITIVOS;
DROP TABLE MONITORES_DISPO;
DROP TABLE PROCESADORES;
DROP TABLE RED_DISPO;
DROP TABLE SUBT_DISPOSITIVOS;
DROP TABLE SUMINISTRO_IMPRE;
DROP TABLE TIPO_DISPOSITIVOS;
/**/
/*ELIMINAR REGISTROS*/
DELETE COMPUTADORES_DISPO;
DELETE DISPOSITIVOS;
DELETE IMPRESORAS_DISPO;

DELETE INTERFAZ_HDD;
DBCC CHECKIDENT (INTERFAZ_HDD,RESEED ,0);

DELETE MARCA_DISPOSITIVOS;
DBCC CHECKIDENT(MARCA_DISPOSITIVOS,RESEED,0);

DELETE MODELOS_DISPOSITIVOS;
DBCC CHECKIDENT(MARCA_DISPOSITIVOS,RESEED,0);

DELETE MONITORES_DISPO;
DBCC CHECKIDENT(MONITORES_DISPO,RESEED,0);

DELETE PROCESADORES;
DBCC CHECKIDENT(PROCESADORES,RESEED,0);

DELETE RED_DISPO;

DELETE SUBT_DISPOSITIVOS;
DBCC CHECKIDENT(SUBT_DISPOSITIVOS,RESEED,0);

DELETE SUMINISTRO_IMPRE;
DBCC CHECKIDENT(PROCESADORES,RESEED,0);

DELETE TIPO_DISPOSITIVOS;
DBCC CHECKIDENT(SUMINISTRO_IMPRE,RESEED,0);

DELETE TIPO_DISPOSITIVOS;
DBCC CHECKIDENT(TIPO_DISPOSITIVOS,RESEED, 0);

DELETE SUBTIPODISPOSITIVOS;
DBCC CHECKIDENT(SUBTIPODISPOSITIVOS,RESEED, 0);

DELETE DISPOSITIVOS;
/**/