CREATE TABLE COMPUTADORES_DISPO (
COMP_SERIAL_V VARCHAR(200) NOT NULL,
COMP_PROCESADOR_INT INTEGER NOT NULL,
COMP_TPALMACENAMIENTO_INT INTEGER NOT NULL,
COMP_CAPALMACENA_INT INTEGER NOT NULL,
COMP_CAPRAM_INT INTEGER NOT NULL
);
ALTER TABLE COMPUTADORES_DISPO ADD CONSTRAINT COMPUTADORES_DISPO_PK PRIMARY KEY CLUSTERED (COMP_SERIAL_V);
 
CREATE TABLE DISPOSITIVOS (
DISPO_SERIAL_V VARCHAR(200) NOT NULL,
DISPO_TIPOID_INT INTEGER NOT NULL,
DISPO_MARCA_INT INTEGER NOT NULL,
DISPO_MODELO_INT INTEGER NOT NULL,
DISPO_ESTADO_INT VARCHAR(2) NOT NULL,
DISPO_DESC_V VARCHAR(200)
);
ALTER TABLE DISPOSITIVOS ADD CONSTRAINT DISPOSITIVOS_PK PRIMARY KEY CLUSTERED (DISPO_SERIAL_V);

CREATE TABLE IMPRESORAS_DISPO (
IMPR_SERIAL_V VARCHAR(200) NOT NULL,
IMPR_LAN_INT INTEGER,
IMPR_WIFI_INT INTEGER,
IMPR_SUMINISTRO_INT INTEGER NOT NULL
); 
ALTER TABLE IMPRESORAS_DISPO ADD CONSTRAINT IMPRESORAS_DISPO_PK PRIMARY KEY CLUSTERED (IMPR_SERIAL_V);

CREATE TABLE INTERFAZ_HDD (
INHD_ID_INT INTEGER IDENTITY(1,1) NOT NULL,
INHD_DESC_V VARCHAR(200) NOT NULL
);
ALTER TABLE INTERFAZ_HDD ADD CONSTRAINT INTERFAZ_HDD_PK PRIMARY KEY CLUSTERED (INHD_ID_INT);

CREATE TABLE MARCA_DISPOSITIVOS (
MARC_ID_INT INTEGER IDENTITY(1,1) NOT NULL,
MARC_DESC_V VARCHAR(200) NOT NULL
);
ALTER TABLE MARCA_DISPOSITIVOS ADD CONSTRAINT MARCA_DISPOSITIVOS_PK PRIMARY KEY CLUSTERED (MARC_ID_INT);

CREATE TABLE MODELOS_DISPOSITIVOS (
MODD_ID_INT INTEGER IDENTITY(1,1) NOT NULL,
MODD_DESC_V VARCHAR(200) NOT NULL
);
ALTER TABLE MODELOS_DISPOSITIVOS ADD CONSTRAINT MODELOS_DISPOSITIVOS_PK PRIMARY KEY CLUSTERED (MODD_ID_INT);

CREATE TABLE MONITORES_DISPO (
MONI_SERIAL_V VARCHAR(200) NOT NULL,
MONI_TIPO_V VARCHAR(200) NOT NULL,
MONI_TPULGADAS_INT INTEGER,
MONI_PVGA_INT INTEGER,
MONI_PDHMI_INT INTEGER,
MONI_PDVI_INT INTEGER,
MONI_PDP_INT INTEGER,
MONI_PUSB_INT INTEGER
);
ALTER TABLE MONITORES_DISPO ADD CONSTRAINT MONITORES_DISPO_PK PRIMARY KEY CLUSTERED (MONI_SERIAL_V);

CREATE TABLE PROCESADORES (
PROS_ID_IN INTEGER IDENTITY(1,1) NOT NULL,
PROS_DESC_V VARCHAR(200) NOT NULL,
PROS_FABRICANTE_INT INTEGER NOT NULL,
PROS_FREC_V VARCHAR(20),
PORC_NUCLEOS_INT INTEGER
);
ALTER TABLE PROCESADORES ADD CONSTRAINT PROCESADORES_PK PRIMARY KEY CLUSTERED (PROS_ID_IN);

CREATE TABLE RED_DISPO (
DRED_SERIAL_V VARCHAR(200) NOT NULL,
DRED_VELOCIDAD_INT INTEGER,
DRED_BANDAS_V VARCHAR(200),
DRED_CATEGORIA_V VARCHAR(200),
DRED_PUERTOS_INT INTEGER,
DRED_ADMINIS_INT INTEGER
);
ALTER TABLE RED_DISPO ADD CONSTRAINT RED_DISPO_PK PRIMARY KEY CLUSTERED (DRED_SERIAL_V);

CREATE TABLE SUBT_DISPOSITIVOS (
STDP_ID_INT INTEGER IDENTITY(1,1) NOT NULL,
STDP_DESC_V VARCHAR(200) NOT NULL
);
ALTER TABLE SUBT_DISPOSITIVOS ADD CONSTRAINT TIPO_DISPOSITIVOS_PK PRIMARY KEY CLUSTERED (STDP_ID_INT);

CREATE TABLE SUMINISTRO_IMPRE (
CONS_ID_INT INTEGER IDENTITY(1,1) NOT NULL,
CONS_TIPO_V VARCHAR(200) NOT NULL,
CONS_CAPACIDAD_INT INTEGER NOT NULL,
CONS_DESC_V VARCHAR(200)
);
ALTER TABLE SUMINISTRO_IMPRE ADD CONSTRAINT SUMINISTRO_IMPRE_PK PRIMARY KEY CLUSTERED (CONS_ID_INT);

CREATE TABLE TIPO_DISPOSITIVOS (
TPD_ID_INT INTEGER IDENTITY(1,1) NOT NULL,
TPD_DESC_V VARCHAR(200) NOT NULL,
TPD_SUBTIPO_INT INTEGER NOT NULL
);
ALTER TABLE TIPO_DISPOSITIVOS ADD CONSTRAINT SUBTIPODISPOSITIVOS_PK PRIMARY KEY CLUSTERED (TPD_ID_INT);

ALTER TABLE DISPOSITIVOS
ADD CONSTRAINT DISPOSITIVOS_MARCA_DISPO_FK FOREIGN KEY ( DISPO_MARCA_INT )
REFERENCES MARCA_DISPOSITIVOS ( MARC_ID_INT );

ALTER TABLE DISPOSITIVOS
ADD CONSTRAINT DISPOSITIVOS_MOD_DISPO_FK FOREIGN KEY ( DISPO_MODELO_INT )
REFERENCES MODELOS_DISPOSITIVOS ( MODD_ID_INT );

ALTER TABLE DISPOSITIVOS
ADD CONSTRAINT DISPOSITIVOS_TIPO_DISPO_FK FOREIGN KEY ( DISPO_TIPOID_INT )
REFERENCES TIPO_DISPOSITIVOS ( TPD_ID_INT );

ALTER TABLE IMPRESORAS_DISPO
ADD CONSTRAINT IMPR_DISPO_DISPO_FK FOREIGN KEY ( IMPR_SERIAL_V )
REFERENCES DISPOSITIVOS ( DISPO_SERIAL_V );

ALTER TABLE IMPRESORAS_DISPO
ADD CONSTRAINT IMPR_DISPO_SUMI_IMPRE_FK FOREIGN KEY ( IMPR_SUMINISTRO_INT )
REFERENCES SUMINISTRO_IMPRE ( CONS_ID_INT );

ALTER TABLE MONITORES_DISPO
ADD CONSTRAINT MONI_DISPO_DISPO_FK FOREIGN KEY ( MONI_SERIAL_V )
REFERENCES DISPOSITIVOS ( DISPO_SERIAL_V );

ALTER TABLE COMPUTADORES_DISPO
ADD CONSTRAINT PCS_DISPO_DISPOSITIVOS_FK FOREIGN KEY ( COMP_SERIAL_V )
REFERENCES DISPOSITIVOS ( DISPO_SERIAL_V );

ALTER TABLE COMPUTADORES_DISPO
ADD CONSTRAINT PCS_DISPO_INTERFAZ_HDD_FK FOREIGN KEY ( COMP_TPALMACENAMIENTO_INT )
REFERENCES INTERFAZ_HDD ( INHD_ID_INT );

ALTER TABLE COMPUTADORES_DISPO
ADD CONSTRAINT PCS_DISPO_PROCESADORES_FK FOREIGN KEY ( COMP_PROCESADOR_INT )
REFERENCES PROCESADORES ( PROS_ID_IN );

ALTER TABLE PROCESADORES
ADD CONSTRAINT PROS_MARCA_DISPO_FK FOREIGN KEY ( PROS_FABRICANTE_INT )
REFERENCES MARCA_DISPOSITIVOS ( MARC_ID_INT );

ALTER TABLE RED_DISPO
ADD CONSTRAINT RED_DISPO_DISPOSITIVOS_FK FOREIGN KEY ( DRED_SERIAL_V )
REFERENCES DISPOSITIVOS ( DISPO_SERIAL_V );

ALTER TABLE TIPO_DISPOSITIVOS
ADD CONSTRAINT TIPO_DISPO_SUBT_DISPO_FK FOREIGN KEY ( TPD_SUBTIPO_INT )
REFERENCES SUBT_DISPOSITIVOS ( STDP_ID_INT );


